export const customThemeVariables = {
  "--sjs-layer-1-background-500": "var(--color-background)",
  "--sjs-layer-1-background-400": "var(--color-sidebar-backgdoud)",
  "--sjs-layer-1-foreground-100": "var(--color-foreground)",
  "--sjs-layer-1-foreground-50": "var(--color-primary)",
  "--sjs-layer-3-background-500": "var(--color-primary)",
  "--sjs-layer-3-foreground-100": "var(--color-foreground)",
  "--sjs-layer-3-foreground-50": "var(--color-primary)",
  "--sjs-layer-2-background-500": "var(--color-muted)",
  "--sjs-layer-2-background-400": "var(--color-muted)",
  "--sjs-special-haze":
    "color-mix(in srgb, var(--color-foreground) 15%, transparent)",
  "--sjs-border-25": "var(--color-border)",
  "--sjs-border-10": "var(--color-border)",
  "--sjs-primary-background-500": "var(--color-foreground)",
  "--sjs-primary-background-10": "var(--color-sidebar-backgdoud)",
  "--sjs-primary-background-400": "var(--color-primary)",
  "--sjs-primary-foreground-100": "var(--color-sidebar-backgdoud)",
  "--sjs-primary-foreground-25":
    "color-mix(in srgb, var(--color-primary-foreground) 25%, transparent)",
  "--sjs-secondary-background-500": "var(--color-primary)",
  "--sjs-secondary-background-25": "#D6378A40",
  "--sjs-secondary-background-10": "var(--color-muted)",
  "--sjs-secondary-foreground-100": "var(--color-primary-foreground)",
  "--sjs-secondary-forecolor-25":
    "color-mix(in srgb, var(--color-primary-foreground) 25%, transparent)",
  "--sjs-semantic-red-background-500": "var(--color-primary)",
  "--sjs-semantic-red-background-10": "#D6378A1A",
  "--sjs-semantic-red-foreground-100": "var(--color-primary-foreground)",
  "--sjs-semantic-green-background-500": "#19B394FF",
  "--sjs-semantic-green-background-10": "#19B3941A",
  "--sjs-semantic-green-foreground-100": "var(--color-primary-foreground)",
  "--sjs-semantic-blue-background-500": "#437FD9FF",
  "--sjs-semantic-blue-background-10": "#437FD91A",
  "--sjs-semantic-blue-foreground-100": "var(--color-primary-foreground)",
  "--sjs-semantic-yellow-background-500": "#FF9814FF",
  "--sjs-semantic-yellow-background-10": "#FF98141A",
  "--sjs-semantic-yellow-foreground-100": "var(--color-primary-foreground)",
  "--sjs-semantic-white-background-500": "var(--color-background)",
  "--sjs-code-gray-700": "var(--color-muted-foreground)",
  "--sjs-code-blue-500": "#326FCAFF",
  "--sjs-code-gray-300": "var(--color-foreground)",
  "--sjs-code-green-500": "#08997CFF",
  "--sjs-code-red-500": "#F41B50FF",
  "--sjs-code-purple-500": "green",
  "--sjs-code-yellow-500": "#F58D06FF",
  "--sjs-code-gray-500": "var(--color-muted-foreground)",
  "--sjs-special-background": "var(--color-background)",
  "--sjs-layer-1-foreground-75": "var(--color-foreground)",
  "--sjs-layer-3-background-400": "transparent",
  "--sjs-special-glow":
    "color-mix(in srgb, var(--color-foreground) 20%, transparent)",
  "--sjs-special-shadow":
    "color-mix(in srgb, var(--color-foreground) 25%, transparent)",
  "--sjs-layer-3-foreground-75": "var(--color-muted-foreground)",
  "--sjs-layer-2-foreground-100": "var(--color-foreground)",
  "--sjs-layer-2-foreground-75": "var(--color-muted-foreground)",
  "--sjs-layer-2-foreground-50":
    "color-mix(in srgb, var(--color-foreground) 50%, transparent)",
  "--sjs-border-25-overlay":
    "color-mix(in srgb, var(--color-foreground) 15%, transparent)",
  "--sjs-secondary-background-400": "var(--color-primary)",
  "--sjs-postcss-fix-slider-path-color": "var(--color-primary)",
  "--sjs-general-backcolor-dim-light": "var(--color-background)",
  "--ctr-editor-border-color": "var(--color-border)",
};
